import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "./theme-provider";
import CustomCursor from "@/components/custom_cursor";
import PageTop from "@/components/page_top";
import "./globals.css";
import Header from "@/components/header";

export const metadata = {
  title: "Hsu Thinzar's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning>
      <body>
        <CustomCursor />
        <ThemeProvider>
          <Header />
          {children}
          <PageTop />
        </ThemeProvider>
      </body>
    </html>
  );
}
